# Generated by Django 5.2 on 2026-06-04 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=32)),
                ('apellido', models.CharField(max_length=32)),
                ('telefono', models.PositiveBigIntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=128, null=True)),
            ],
            options={
                'ordering': ['apellido'],
            },
        ),
        migrations.CreateModel(
            name='Operador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=32, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Operadores',
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='Sitio',
            fields=[
                ('internal_id', models.BigAutoField(primary_key=True)),
                ('sigla_id', models.CharField(max_length=64, unique=True)),
                ('nombre', models.CharField(max_length=64, verbose_name='Nombre')),
                ('direccion', models.CharField(max_length=120, verbose_name='Dirección')),
                ('localidad', models.CharField(max_length=50, verbose_name='Localidad')),
                ('municipio', models.CharField(max_length=50, verbose_name='Municipio')),
                ('provincia', models.CharField(choices=[('Buenos Aires', 'Buenos Aires'), ('CABA', 'CABA'), ('Catamarca', 'Catamarca'), ('Chaco', 'Chaco'), ('Chubut', 'Chubut'), ('Córdoba', 'Córdoba'), ('Corrientes', 'Corrientes'), ('Entre Ríos', 'Entre Ríos'), ('Formosa', 'Formosa'), ('Jujuy', 'Jujuy'), ('La Pampa', 'La Pampa'), ('La Rioja', 'La Rioja'), ('Mendoza', 'Mendoza'), ('Misiones', 'Misiones'), ('Neuquen', 'Neuquen'), ('Río Negro', 'Río Negro'), ('Salta', 'Salta'), ('San Juan', 'San Juan'), ('San Luis', 'San Luis'), ('Santa Cruz', 'Santa Cruz'), ('Santa Fe', 'Santa Fe'), ('Santiago del Estero', 'Santiago del Estero'), ('Tierra del Fuego', 'Tierra del Fuego'), ('Tucumán', 'Tucumán')], max_length=19, verbose_name='Provincia')),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Latitud')),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Longitud')),
                ('proyecto', models.CharField(max_length=64, verbose_name='Proyecto')),
                ('tipo', models.CharField(max_length=64, verbose_name='Tipo')),
                ('estructura', models.CharField(max_length=64, verbose_name='Estructura')),
                ('altura', models.PositiveSmallIntegerField(verbose_name='Altura')),
                ('acceso', models.CharField(choices=[('INDEPENDIENTE', 'INDEPENDIENTE'), ('LOCADOR', 'LOCADOR')], max_length=14, verbose_name='Acceso')),
                ('aviso', models.BooleanField(default=False, verbose_name='Requiere aviso al locador')),
                ('candado_calle', models.CharField(choices=[('BLUETOOTH', 'BLUETOOTH'), ('PROPIO', 'PROPIO'), ('NUMÉRICO', 'NUMÉRICO'), ('OTRO', 'OTRO'), ('N/A', 'N/A')], max_length=9, verbose_name='Candado Calle')),
                ('candado_sitio', models.CharField(choices=[('BLUETOOTH', 'BLUETOOTH'), ('PROPIO', 'PROPIO'), ('NUMÉRICO', 'NUMÉRICO'), ('OTRO', 'OTRO'), ('N/A', 'N/A')], max_length=9, verbose_name='Candado Sitio')),
                ('combinacion', models.CharField(blank=True, max_length=11, null=True, verbose_name='Combinación')),
                ('conflicto', models.BooleanField(default=False, verbose_name='Acceso conflictivo')),
                ('procedimiento', models.TextField(blank=True, null=True, verbose_name='Procedimiento')),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Planificado', 'Planificado'), ('Cancelado', 'Cancelado'), ('Desmontado', 'Desmontado')], max_length=14, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Titular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=32, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Titulares',
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='MP',
            fields=[
                ('id', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('fecha_de_plan', models.DateField()),
                ('estado', models.CharField(max_length=32)),
                ('alcance', models.CharField(max_length=64)),
                ('enlace', models.URLField()),
                ('sitio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sitios.sitio')),
            ],
        ),
        migrations.CreateModel(
            name='Suministro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distribuidora', models.CharField(blank=True, max_length=32, null=True)),
                ('cuenta', models.CharField(blank=True, max_length=18, null=True)),
                ('medidor', models.CharField(blank=True, max_length=18, null=True)),
                ('direccion', models.CharField(blank=True, max_length=64, null=True)),
                ('sitio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='suministros', to='sitios.sitio')),
                ('titular', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='suministros', to='sitios.titular')),
            ],
            options={
                'ordering': ['titular'],
            },
        ),
        migrations.CreateModel(
            name='Cellowner',
            fields=[
                ('contacto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sitios.contacto')),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cellowners', to='sitios.operador')),
            ],
            bases=('sitios.contacto',),
        ),
        migrations.CreateModel(
            name='Celda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_operador', models.CharField(max_length=64)),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='celdas', to='sitios.operador')),
                ('sitio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='celdas', to='sitios.sitio')),
                ('suministro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='celdas', to='sitios.suministro')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='celdas', to='sitios.cellowner')),
            ],
        ),
        migrations.CreateModel(
            name='Locador',
            fields=[
                ('contacto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sitios.contacto')),
                ('relacion', models.CharField(blank=True, max_length=24, null=True)),
                ('sitios', models.ManyToManyField(related_name='locadores', to='sitios.sitio')),
            ],
            options={
                'verbose_name_plural': 'Locadores',
            },
            bases=('sitios.contacto',),
        ),
    ]
