# Generated by Django 5.2 on 2026-06-04 23:33

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('sitios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acceso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_desde', models.DateField(verbose_name='Fecha de inicio')),
                ('fecha_hasta', models.DateField(verbose_name='Fecha de fin')),
                ('hora_desde', models.TimeField(verbose_name='Hora desde')),
                ('hora_hasta', models.TimeField(verbose_name='Hora hasta')),
                ('empresa', models.CharField(max_length=128, verbose_name='Empresa')),
                ('afectacion', models.BooleanField(default=False, verbose_name='¿Hay afectación de servicio?')),
                ('riesgo_electrico', models.BooleanField(default=False, verbose_name='¿Hay riesgo eléctrico?')),
                ('altura', models.BooleanField(default=False, verbose_name='¿Incluye trabajo en altura?')),
                ('permiso_generado', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Acceso',
                'verbose_name_plural': 'Accesos',
            },
        ),
        migrations.CreateModel(
            name='CambioDeEquipos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('antenas_actual', models.TextField(verbose_name='Antenas RF actuales')),
                ('antenas', models.TextField(verbose_name='Antenas RF')),
                ('enlaces_actual', models.TextField(verbose_name='Radioenlaces actuales')),
                ('enlaces', models.TextField(verbose_name='Radioenlaces')),
                ('rru_actual', models.TextField(verbose_name='RRU actual')),
                ('rru', models.TextField(verbose_name='RRU')),
                ('piso', models.TextField(verbose_name='Cota 0')),
                ('energia', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Potencia (kW)')),
            ],
            options={
                'verbose_name': 'Cambio de Equipos',
                'verbose_name_plural': 'Cambios de Equipos',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=32, unique=True)),
                ('visible', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'Clientes',
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='Motivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=32, unique=True)),
                ('visible', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'Motivos',
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='OC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=12, null=True, verbose_name='N° de OC')),
                ('moneda', models.CharField(blank=True, choices=[('ARS', '$'), ('USD', 'u$s')], default='ARS', max_length=3, null=True, verbose_name='Moneda')),
                ('condicion', models.CharField(blank=True, choices=[('NETO_7', 'Neto 7d'), ('NETO_30', 'Neto 30d'), ('ANTICIPO_30', 'Anticipo 30%'), ('ANTICIPO_50', 'Anticipo 50%')], default='NETO_30', max_length=12, null=True, verbose_name='Condición')),
                ('contratista', models.CharField(blank=True, max_length=32, null=True, verbose_name='Contratista')),
                ('costo', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Costo')),
                ('comprador', models.CharField(blank=True, choices=[('1', 'Unidad de negocios 1'), ('2', 'Unidad de negocios 2')], default='1', max_length=2, null=True, verbose_name='Comprador')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
                ('apellido', models.CharField(max_length=64)),
                ('dni', models.PositiveIntegerField()),
                ('telefono', models.PositiveBigIntegerField()),
                ('aprobado', models.BooleanField(default=True)),
                ('acceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal', to='tkts.acceso')),
            ],
            options={
                'verbose_name_plural': 'Personal',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Ticket')),
                ('_estado_id', models.IntegerField(choices=[(0, 'Abierto'), (1, 'En facturación'), (2, 'Cerrado'), (3, 'Rechazado'), (4, 'Abierto'), (5, 'Cerrado'), (6, 'Rechazado')])),
                ('inicio', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Inicio')),
                ('nombre', models.CharField(max_length=64, verbose_name='Nombre Completo')),
                ('email', models.EmailField(max_length=256, verbose_name='Email')),
                ('telefono', models.PositiveIntegerField(verbose_name='Teléfono')),
                ('prioridad', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Prioridad')),
                ('problema', models.TextField(verbose_name='Problema')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Link de documentación')),
                ('solucion', models.TextField(blank=True, null=True, verbose_name='Solución')),
                ('programada', models.DateField(blank=True, null=True, verbose_name='Fecha programada')),
                ('cierre', models.DateField(blank=True, null=True, verbose_name='Fecha de cierre')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('ultima_modificacion', models.DateTimeField(auto_now=True, null=True, verbose_name='Última modificación')),
                ('acceso', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ticket', to='tkts.acceso')),
                ('cambio_de_equipos', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ticket', to='tkts.cambiodeequipos')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='tkts.cliente', verbose_name='Cliente')),
                ('motivo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='tkts.motivo', verbose_name='Motivo')),
                ('oc', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ticket', to='tkts.oc')),
                ('sitio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sitios.sitio', verbose_name='Sitio')),
                ('usuario_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets_asignados', to='tkts.usuario', verbose_name='Usuario asignado')),
            ],
        ),
    ]
