# Generated by Django 5.2 on 2026-06-04 23:33

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('code', models.SmallIntegerField()),
                ('data', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TicketChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('changed_data', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
            ],
        ),
    ]
