# Generated by Django 5.2 on 2026-06-04 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logger', '0001_initial'),
        ('tkts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketchangelog',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cambios', to='tkts.ticket'),
        ),
        migrations.AddField(
            model_name='ticketchangelog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tkts.usuario'),
        ),
    ]
